version: "3"

services:
  nats:
    command: -m 8222
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - nats-dash
  worker:
    build:
      context: "./"
    links:
      - nats
    environment:
      - "NATS_URI=nats://nats:4222"
    networks:
      - nats-dash
  fluent-bit:
    image: fluent/fluent-bit:1.0
    links:
      - nats
    networks:
      - nats-dash
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./fluent_bit.conf:/fluent-bit/etc/fluent-bit.conf:ro"
  log-generator:
    image: chentex/random-logger:latest
    depends_on:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        #fluentd-address: "fluent-bit"
        tag: "logger.example"
        #mode: "non-blocking"
        #max-buffer-size: "2m"
        #fluentd-async-connect: "true"
networks:
  nats-dash:
volumes:
  nats:
